app2/urls.py
from django.urls import path
from app2.views import *
app_name = 'app2'

urlpatterns = [
    path('sthird/', sthird, name = 'sthird'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/', first, name = 'first'),
    path('second/',second, name = 'second'),
    path('app2/', include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')
def second(request):
    return render(request,'second.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def sthird(request):
    return render(request,'sthird.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is First HTML page</h1>
        <a href="{% url 'second' %}">Second HTML</a><br>
        <a href="{% url 'app2:sthird' %}">Third HTML</a>
    </center>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is Second HTML page</h1>
        <a href="{% url 'first' %}">First HTML</a><br>
        <a href="{% url 'app2:sthird' %}">Third HTML</a>
    </center>
</body>
</html>

templates/sthird.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is Third HTML page</h1>
        <h2>This is done through specific url</h2>
        <a href="{% url 'first' %}">First HTML</a><br>
        <a href="{% url 'second' %}">Second HTML</a>

    </center>
</body>
</html>